CREATE TABLE "GCG_6936_BAR_SERIALS"(
 "TERMINAL" CHAR(3),
 "RPTID" CHAR(6),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SERIAL_NUMBER" CHAR(30));

CREATE INDEX "GCG_6936_BAR_SERIALS" ON "GCG_6936_BAR_SERIALS"("TERMINAL", "RPTID", "JOB", "SUFFIX");