CREATE TABLE "GCG_6936_MAT_GROUP"(
 "MAT_GROUP" CHAR(20),
 "DESCRIPTION" CHAR(50),
 "HYDRO_SHELL" INTEGER,
 "NITROGEN_SHELL" INTEGER,
 "HYDRO_SEAT" INTEGER,
 "NITROGEN_SEAT" INTEGER,
 "AIR_SEAT" INTEGER );

CREATE INDEX "GCG_6936_MAT_GROUP" ON "GCG_6936_MAT_GROUP"("MAT_GROUP");