CREATE TABLE "GCG_6936_PO_SERIALS"(
 "PURCHASE_ORDER" CHAR(7),
 "RECORD_NO" CHAR(4),
 "SERIAL_NUMBER" CHAR(30),
 "RECEIVED" BIT DEFAULT '0' NOT NULL,
 "HEAT" CHAR(15),
 "BONNET_HEAT" CHAR(15),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "WIPFG" BIT DEFAULT '0' NOT NULL,
 "DATE_CREATED" DATE,
 "SALES_ORDER" CHAR(7),
 "SALES_ORDER_LINE" CHAR(4),
 "H_MAT" CHAR(50),
 "B_MAT" CHAR(50),
 "LST_CHG_DATE" DATETIME,
 "LST_CHG_USER" CHAR(8),
 "LST_CHG_PRG" CHAR(50),
 "DATE_ADDED" DATE DEFAULT CURDATE() );
 
CREATE INDEX "GCG_6936_PO_SERIALS" USING 0 ON "GCG_6936_PO_SERIALS"("PURCHASE_ORDER", "RECORD_NO", "SERIAL_NUMBER", "SALES_ORDER", "SALES_ORDER_LINE");