CREATE TABLE "GCG_6936_HOLD_TIME"(
 "CODE" CHAR(10),
 "DESCRIPTION" CHAR(30),
 "MTR_TIME_1" INTEGER,
 "MTR_TIME_2" INTEGER,
 "MTR_TIME_3" INTEGER);

CREATE INDEX "GCG_6936_HOLD_TIME" ON "GCG_6936_HOLD_TIME"("CODE");